### ISSUE TITLE
 Node version constraint is incorrect.

### ISSUE THREAD

**Issue by molvqingtai** [imtaotao/danmu#18]
Hey, I want to use this library, but due to the node version constraint, it cannot be greater than v20.0.x. I have to switch to v20 since I'm using v22.x.
Maybe it should be changed to "node": ">=20.0.0"?

**Comment by imtaotao** [comment]
> Hey, I want to use this library, but due to the node version constraint, it cannot be greater than v20.0.x. I have to switch to v20 since I'm using v22.x.
> Maybe it should be changed to "node": ">=20.0.0"?

yes

**Comment by imtaotao** [comment]
Fixed
