### ISSUE TITLE
unsafe-eval error

### ISSUE THREAD

**Issue by molvqingtai** [imtaotao/danmu#19]
Using eval can lead to unsafe-eval errors, especially in certain specific environments where it is not allowed, such as browser extension environments.

https://github.com/imtaotao/danmu/blob/a2c064e13c4c7379521a09eb590aafd68233e1e9/src/utils.ts#L20

![image](https://github.com/user-attachments/assets/a62dad4b-2e0c-468a-868d-5ffc88ccf125)

**Comment by imtaotao** [comment]
这个问题是你的站点有 csp 策略，我不确定 csp 策略下能不能执行 new function，你可以尝试一下，如果不行的话，得写一个表达式的 parser 了

**Comment by molvqingtai** [comment]
> 这个问题是你的站点有 csp 策略，我不确定 csp 策略下能不能执行 new function，你可以尝试一下，如果不行的话，得写一个表达式的 parser 了

浏览器扩展直接不支持 eval 和 new function , 为了防止已上架的插件动态执行恶意代码

**Comment by imtaotao** [comment]
我抽空写个数学计算表达式的 parser 吧，不用 eval 了，但是会慢很多

**Comment by imtaotao** [comment]
你的那个 pr，可以先把 package.json 那个改动提一下。

**Comment by imtaotao** [comment]
修复了，可以更新版本再看看。
