### ISSUE TITLE
支持开始阶段，弹幕全屏充满吗？

### ISSUE THREAD

**Issue by hanmingpan** [imtaotao/danmu#24]
看了一下文档，好像没有这个配置项，应该是不支持吧？

**Comment by imtaotao** [comment]
可以的，这个功能不属于内核要支持的能力，业务侧可以很好做，这里是例子，不过是点击之后全屏，你如果要一开始就全屏，直接在初始化之后，把 DOM 全屏就好了
https://github.com/imtaotao/danmu/blob/master/demo/src/components/danmu/Container.tsx#L41-L52

![QQ_1732702117924](https://github.com/user-attachments/assets/acbf7dbb-42b7-475d-ba53-432f05697732)
